using RealisticDependencies.Logger;

namespace BehavioralPatterns.Visitor;

public class SaleReport: Report
{
    public SaleReport(IApplicationLogger logger, DateTime date, decimal totalSales) : base(logger) {
        CreatedBy = "SalesDataRobot";
        CreatedOn = date;
        TotalSales = totalSales;
    }

    public decimal TotalSales { get; private set; }

    public override void Print() {
        _logger.LogInfo($"=== 💸 Sales Data for {CreatedOn} 💸 ===", ConsoleColor.Green);
        _logger.LogInfo($"=== Generated By: {CreatedBy} ===", ConsoleColor.Green);
        _logger.LogInfo($"- Total Sales Today: ${TotalSales}", ConsoleColor.Green);
        _logger.LogInfo("\n");
    }
}
